/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package stockholm.forms;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import stockholm.data_access.getInvoiceRandomCode;
import stockholm.data_access.sl_Business;
import stockholm.data_access.sl_Category;
import stockholm.data_access.sl_Stock;
import stockholm.data_access.sl_Invoice;
import stockholm.user_interface.cl_Invoice;
import stockholm.user_interface.cl_InvoiceBusiness;
import stockholm.user_interface.cl_InvoiceStock;

/**
 *
 * @author semih
 */
public class frmProcessStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBuyStock
     */
    public frmProcessStock() {
        initComponents();
        startProg();
    }

    public frmProcessStock(String type) {
        _type = type;

        initComponents();
        startProg();

    }

    private String _type = "";
    private DefaultListModel<String> listModel;
    private sl_Business sBusiness = new sl_Business();
    private sl_Stock sStock = new sl_Stock();
    private sl_Invoice sInvoice = new sl_Invoice();
    private cl_InvoiceBusiness business = new cl_InvoiceBusiness();
    private cl_InvoiceStock stock = new cl_InvoiceStock();
    private cl_Invoice invoice = new cl_Invoice();

    private void startProg() {
        listModel = (DefaultListModel<String>) lstList.getModel();

        if (_type.equals("buy")) {
            this.setTitle("Stok Alım");
            txtKDV.setEditable(true);
            btnProcess.setText("Alım Yap");
        } else if (_type.equals("sell")) {
            this.setTitle("Stok Satış");
            txtKDV.setEditable(false);
            btnProcess.setText("Satş Yap");
        } else {
            JOptionPane.showMessageDialog(null, "Hatalı pencere seçimi olduğu için işlem gerçekleşmiyor.", "Hatalı İşlem", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

        txtDate.setText(getDateNow());

    }

    private String getDateNow() {
        LocalDate dateNow = LocalDate.now();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        return dateNow.format(format).toString();
    }

    private String getInvoiceID() {
        String invoice;
        while (true) {
            invoice = getInvoiceRandomCode.getInvoice();
            if (!(sInvoice.isThereInvoice(invoice))) {
                return invoice;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        btnInvoiceGenereteID = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtStockID = new javax.swing.JTextField();
        txtStockName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtSellPrice = new javax.swing.JTextField();
        spnAmount = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtKDV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        btnDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBusinessID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBusinessName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnProcess = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("null");

        jPanel1.setBackground(new java.awt.Color(230, 240, 245));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel5.setText("Fatura Numarası : ");

        txtInvoiceID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        btnInvoiceGenereteID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btnInvoiceGenereteID.setText("Üret");
        btnInvoiceGenereteID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvoiceGenereteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceGenereteIDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel6.setText("Tarih : ");

        txtDate.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtDate.setToolTipText("\"ENTER\" tuşu ile güncel tarihi getirin");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvoiceGenereteID)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvoiceGenereteID)
                    .addComponent(jLabel6)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel3.setText("Stok Kodu : ");

        txtStockID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtStockID.setToolTipText("\"ENTER\" tuşu ile stok bilgilerini getirin");
        txtStockID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockIDActionPerformed(evt);
            }
        });

        txtStockName.setEditable(false);
        txtStockName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtStockName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel7.setText("Miktar : ");

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel1.setText("Birim Fiyat : ");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel2.setText("Toplam Fiyat : ");

        txtPrice.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        txtSellPrice.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtSellPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellPriceActionPerformed(evt);
            }
        });

        spnAmount.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        spnAmount.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1L)));
        spnAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAmountStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel4.setText("Stok Adı : ");

        btnAdd.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btnAdd.setText("Ekle");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtKDV.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel10.setText("KDV Oran : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStockID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStockID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(11, 11, 11))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N

        lstList.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lstList.setModel(new DefaultListModel());
        lstList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstList);

        btnDelete.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btnDelete.setText("Kaldır");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(11, 11, 11))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel8.setText("Firma Kodu : ");

        txtBusinessID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtBusinessID.setToolTipText("\"\"ENTER\" tuşu ile firma bilgilerin i getirin");
        txtBusinessID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBusinessID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusinessIDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel9.setText("Firma Adı : ");

        txtBusinessName.setEditable(false);
        txtBusinessName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        txtBusinessName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusinessID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBusinessID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnProcess.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnProcess.setText("null");
        btnProcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProcess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListMouseClicked
        // TODO add your handling code here:
        String regex = "[+]";
        String[] text = lstList.getSelectedValue().split(regex);
        spnAmount.setModel(new SpinnerNumberModel(Integer.parseInt(text[2].trim()), 0, sStock.getAmount(text[0].trim()), 1));

        txtStockID.setText(text[0].trim());
        txtStockName.setText(text[1].trim());
        //spnAmount.setValue(text[2].trim());
        txtPrice.setText(text[3].trim());
        txtKDV.setText(text[4].trim());
        txtSellPrice.setText(text[5].trim());
    }//GEN-LAST:event_lstListMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        listModel.remove(lstList.getSelectedIndex());
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (stock.chkSetID(txtStockID.getText()) && stock.chkSetName(txtStockName.getText()) && stock.chkSetPrice(txtPrice.getText()) && stock.chkSetKdv(txtKDV.getText()) && stock.chkSetSellPrice(txtSellPrice.getText()) && stock.chkSetAmount(spnAmount.getValue().toString())) {
            boolean isThere = false;

            if (listModel.size() > 0) {
                for (int i = 0; i < listModel.size(); i++) {
                    if (listModel.get(i).contains(stock.getID())) {
                        isThere = true;
                    }
                }
            }

            if (stock.getAmount() > 0 && !(isThere)) {
                listModel.addElement(stock.getID().concat(" + ").concat(stock.getName()).concat(" + ").concat(stock.getAmount() + "").concat(" + ").concat(stock.getPrice().toString()).concat(" + ").concat(stock.getKdv().toString()).concat(" + ").concat(stock.getSellPrice().toString()));
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnInvoiceGenereteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceGenereteIDActionPerformed
        // TODO add your handling code here:
        txtInvoiceID.setText(getInvoiceID());
    }//GEN-LAST:event_btnInvoiceGenereteIDActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        if (invoice.chkSetDate(txtDate.getText()) && invoice.chkSetInvoice(txtInvoiceID.getText())) {
            if (!(sInvoice.isThereInvoice(invoice.getInvoice()))) {
                if (listModel.size() > 0) {
                    if (sBusiness.isThereID(txtBusinessID.getText())) {
                        business = sBusiness.getInformationBusinessInvoice(txtBusinessID.getText());
                        business.setInvoice(invoice.getInvoice());

                        boolean isStock = true;
                        String[] text;
                        cl_InvoiceStock[] stocks = new cl_InvoiceStock[listModel.size()];

                        for (int i = 0; i < listModel.size(); i++) {
                            text = listModel.get(i).split("[+]");

                            if (_type.equals("sell")) {
                                if (sStock.getAmount(text[0].trim()) - Integer.parseInt(text[2].trim()) < 0) {
                                    isStock = false;

                                    stock.setID(text[0].trim());
                                    stock.setName(text[1].trim());
                                    stock.setAmount(Integer.parseInt(text[2].trim()));

                                    break;
                                }
                            }

                            stock = sStock.getInformationStockInvoice(text[0].trim());

                            stock.setInvoice(invoice.getInvoice());
                            stock.setPrice(new BigDecimal(text[3].trim()).divide(BigDecimal.ONE.add(new BigDecimal((String) text[4].trim()).divide(new BigDecimal("100"), 10, RoundingMode.HALF_UP)), 2, RoundingMode.HALF_UP));
                            stock.setKdv(new BigDecimal(text[4].trim()));
                            stock.setSellPrice(new BigDecimal(text[5].trim()));
                            stock.setAmount(Integer.parseInt(text[2].trim()));
                            stock.setCategoryName(new sl_Category().getCategoryName(stock.getCategoryID()));

                            stocks[i] = stock;
                        }

                        if (isStock) {
                            if (_type.equals("buy")) {
                                invoice.setType("ALIŞ");
                            } else {
                                invoice.setType("SATIŞ");
                            }

                            invoice.setProducts(listModel.getSize());

                            if (sInvoice.isAdd(invoice, business, stocks)) {
                                JOptionPane.showMessageDialog(null, invoice.getType().concat(" işlemi başarıyla gerçekleşti."), "Başarılı İşlem", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(null, invoice.getType().concat(" işlemi yapılırken bir hata ile karşılaşıldı."), "Hatalı İşlem", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            //stok yok
                            JOptionPane.showMessageDialog(null, "Listenizde bulunan bir ürünün stoğu istediğiniz miktarı karşılamıyor!\n* Ürün Kodu : ".concat(stock.getID()).concat("\n* Ürün Adı : ").concat(stock.getName()).concat("\n* Bulunan Stoğu : ").concat(stock.getAmount() + "").concat("\n* İstediğiniz Miktar : ").concat(sStock.getAmount(stock.getID()) + ""), "Yetersiz Ürün", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        //firma id yanlış
                        JOptionPane.showMessageDialog(null, "Girdiğiniz firma kodu hatalı, firma bulunamadı.", "Firma Bulunamadı", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    //liste boş
                    JOptionPane.showMessageDialog(null, "Ürün listesi boş olduğu için işlem yapılamıyor.", "Boş Liste", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                //faturo no kayıtlı
                JOptionPane.showMessageDialog(null, "Girdiğiniz fatura numarası kayıtlı! Lütfen kontrol edin ya da yeni fatura no üretin.", "Kayıtlı Fatura Numarası", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //tarih ve fatura no hatalı
            JOptionPane.showMessageDialog(null, "Girdiğiniz format hatalıdır,\n\n* Girdiğiniz tarih formatı '01.01.2000' tarzında olmalı\n* Fatura numarası boş geçilemez", "Hatalı Format", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void txtStockIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockIDActionPerformed
        // TODO add your handling code here:
        SpinnerNumberModel spnModelAmount = new SpinnerNumberModel(0, 0, 0, 0);

        if (_type.equals("sell")) {
            if (sStock.isThereID(txtStockID.getText())) {
                stock = sStock.getInformationStockInvoice(txtStockID.getText());
                txtStockName.setText(stock.getName());
                txtPrice.setText(stock.getPrice().add(stock.getKdv().multiply(stock.getPrice()).divide(new BigDecimal(100), 2, RoundingMode.HALF_UP)).toString());
                txtSellPrice.setText("0");
                txtKDV.setText(stock.getKdv().toString());

                spnModelAmount = new SpinnerNumberModel(0, 0, stock.getAmount(), 1);
            } else {

            }
        } else if (_type.equals("buy")) {
            if (sStock.isThereID(txtStockID.getText())) {
                stock = sStock.getInformationStockInvoice(txtStockID.getText());
                txtStockName.setText(stock.getName());

                spnModelAmount = new SpinnerNumberModel(0, 0, 9000000, 1);
            } else {

            }
        } else {

        }

        spnAmount.setModel(spnModelAmount);
    }//GEN-LAST:event_txtStockIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
        txtDate.setText(getDateNow());
    }//GEN-LAST:event_txtDateActionPerformed

    private void spnAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAmountStateChanged
        // TODO add your handling code here:
        if (stock.chkSetPrice(txtPrice.getText())) {
            txtSellPrice.setText(stock.getPrice().multiply(new BigDecimal(spnAmount.getValue().toString())).toString());
        }
    }//GEN-LAST:event_spnAmountStateChanged

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
        if (stock.chkSetPrice(txtPrice.getText())) {
            txtSellPrice.setText(stock.getPrice().multiply(new BigDecimal(spnAmount.getValue().toString())).toString());
        }
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtSellPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellPriceActionPerformed
        // TODO add your handling code here:
        if (stock.chkSetPrice(txtPrice.getText())) {
            txtSellPrice.setText(stock.getPrice().multiply(new BigDecimal(spnAmount.getValue().toString())).toString());
        }
    }//GEN-LAST:event_txtSellPriceActionPerformed

    private void txtBusinessIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusinessIDActionPerformed
        // TODO add your handling code here:
        if (sBusiness.isThereID(txtBusinessID.getText())) {
            business = sBusiness.getInformationBusinessInvoice(txtBusinessID.getText());
            txtBusinessName.setText(business.getBusinessName());
        }else{
            txtBusinessName.setText("(BİLGİ SAĞLANAMADI)");
        }
    }//GEN-LAST:event_txtBusinessIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInvoiceGenereteID;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstList;
    private javax.swing.JSpinner spnAmount;
    private javax.swing.JTextField txtBusinessID;
    private javax.swing.JTextField txtBusinessName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtKDV;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSellPrice;
    private javax.swing.JTextField txtStockID;
    private javax.swing.JTextField txtStockName;
    // End of variables declaration//GEN-END:variables
}
